In [2]:
import numpy as np
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt 
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn import metrics

df = pd.read_csv(r'C:\Users\User\Downloads\wifi_localization.txt', sep="\t", header=None, 
                 names=["s1", "s2", "s3", "s4", "s5", "s6", "s7", "r"])
X = df.iloc[:, :7]
y = df.iloc[:, 7]
X_train, X_test, y_train, y_test = train_test_split(X, y,  test_size=0.2)
log_full = linear_model.LogisticRegression()
log_full.fit(X_train, y_train)
full_predict = log_full.predict(X_test)
print("Accuracy", metrics.accuracy_score(y_test, full_predict))
a = []
for i in y_test:
    a.append(i)
b = []
for i in full_predict:
    b.append(i)
np.set_printoptions(suppress=True)
for i in range(len(a)):
    if a[i]!=b[i]:
        print(log_full.predict_proba([X_test.iloc[i,:]]))

Accuracy 0.965
[[0.0000007  0.87498374 0.12501556 0.        ]]
[[0.0000008  0.20107749 0.79892171 0.        ]]
[[0.00336155 0.00000019 0.93764006 0.0589982 ]]
[[0.0002442  0.         0.35236101 0.64739479]]
[[0.00000383 0.80435704 0.19563913 0.        ]]
[[0.00003527 0.81379735 0.18616739 0.        ]]
[[0.00000025 0.89313309 0.10686666 0.        ]]
[[0.10940588 0.00028796 0.89029121 0.00001495]]
[[0.02707177 0.         0.3050082  0.66792003]]
[[0.0000006  0.57324157 0.4267578  0.00000003]]
[[0.00002946 0.70026739 0.29970315 0.        ]]
[[0.0000001  0.17188281 0.82811708 0.00000001]]
[[0.00001141 0.130209   0.86977959 0.        ]]
[[0.00000487 0.66597622 0.33401892 0.        ]]


C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
